spring:
  name: serverBase
  datasource:
    url: jdbc:mysql://localhost:3306/baseServer?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop #none
    show-sql: true
spring doc:
  swagger-ui:
    path: /swagger-ui.html