spring:
  name: serverBase
  datasource:
    url: jdbc:mysql://localhost:3306/baseServer?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #none
    show-sql: true